# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "kananlib"
cmake-before=""" 
add_compile_options($<$<CXX_COMPILER_ID:MSVC>:/MP>)
"""
cmake-after="""
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    # The project is being built standalone
    message(STATUS "kananlib: Building standalone")
    set(KANANLIB_STANDALONE_BUILD ON)
else()
    # The project is being included as part of another project
    message(STATUS "kananlib: Building as part of another project")
    set(KANANLIB_STANDALONE_BUILD OFF)
endif()
"""

[options]
KANANLIB_FETCH_BDDISASM = false
KANANLIB_FETCH_SPDLOG = false
KANANLIB_STANDALONE_BUILD = false

[conditions]
fetch-bddisasm = "KANANLIB_FETCH_BDDISASM OR KANANLIB_STANDALONE_BUILD"
fetch-spdlog = "KANANLIB_FETCH_SPDLOG OR KANANLIB_STANDALONE_BUILD"

[fetch-content.bddisasm]
condition = "fetch-bddisasm"
git = "https://github.com/bitdefender/bddisasm"
tag = "v1.37.0"
shallow = true

[fetch-content.spdlog]
condition = "fetch-spdlog"
git = "https://github.com/gabime/spdlog"
tag = "v1.12.0"
shallow = true

[template.kananlib-template]
type = "static"
sources = ["src/*.cpp", "include/**.hpp"]
include-directories = ["include"]
compile-features = ["cxx_std_20"]
link-libraries = [
    "bddisasm::bddisasm", 
    "spdlog::spdlog", 
    "shlwapi"
]

[target.kananlib]
type = "kananlib-template"
cmake-after="""
if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    message(STATUS "MSVC")
    target_compile_options(kananlib PRIVATE /EHa)
else()
    message(STATUS "CLANG")
    target_compile_options(kananlib PRIVATE
        -fasynchronous-unwind-tables
        -fexceptions
        -fms-extensions
    )
endif()
"""

[target.kananlib-nolog]
type = "kananlib-template"
compile-definitions = ["SPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_OFF"]
cmake-after="""
if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    target_compile_options(kananlib-nolog PRIVATE /EHa)
else()
    target_compile_options(kananlib-nolog PRIVATE
        -fasynchronous-unwind-tables
        -fexceptions
        -fms-extensions
    )
endif()
"""

# TODO: define a target for each of your executables/libraries like this:
#[target.myexecutable]
#type = "executable" # static, shared
#sources = ["src/kananlib/*.cpp", "include/kananlib/*.hpp"]
#include-directories = ["include"]
#compile-features = ["cxx_std_11"]
#link-libraries = ["target-or-library"]
