name: Dev Release
on: [push, pull_request, workflow_dispatch]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [kananlib, kananlib-nolog]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: recursive
          persist-credentials: false

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 18 2026" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{matrix.target}}

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: recursive
          persist-credentials: false

      - name: Configure CMake
        run: cmake -S ${{github.workspace}}/test -B ${{github.workspace}}/test/build -G "Visual Studio 18 2026" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build all tests
        run: cmake --build ${{github.workspace}}/test/build --config ${{env.BUILD_TYPE}}

      - name: Run all tests
        run: ctest --test-dir ${{github.workspace}}/test/build -C ${{env.BUILD_TYPE}} --output-on-failure

